#!/bin/bash

echo "🔍 Device MAC Address Discovery Tool"
echo "===================================="
echo ""

echo "📋 This script helps you find MAC addresses for setting up static DHCP leases"
echo ""

echo "📡 Current Network Devices (from Asus Router):"
echo "----------------------------------------------"
echo "1. Open Asus router admin: http://192.168.1.1"
echo "2. Go to Advanced Settings → LAN → DHCP Server"
echo "3. Look at 'Client List' or 'Manually Assigned IP List'"
echo "4. Note the MAC addresses for your devices"
echo ""

echo "🔧 Device-Specific MAC Address Locations:"
echo "------------------------------------------"
echo ""

echo "🍎 macOS Devices (like your Mac):"
echo "- System Settings → WiFi → [Network Name] → Details"
echo "- Look for 'Hardware Address' or 'MAC Address'"
echo ""

echo "🪟 Windows Devices:"
echo "- Open Command Prompt: cmd"
echo "- Run: ipconfig /all"
echo "- Look for 'Physical Address' under your network adapter"
echo ""

echo "📱 iPad/iPhone:"
echo "- Settings → WiFi → [Tap network name] → Info icon (i)"
echo "- Look for 'MAC ADDRESS' or 'Wi-Fi Address'"
echo ""

echo "🎮 Gaming Consoles:"
echo ""
echo "PS5:"
echo "- Settings → Network → Settings → View Connection Status"
echo "- Look for 'MAC Address'"
echo ""
echo "Nintendo Switch:"
echo "- System Settings → Internet → Internet Settings → [Your Network]"
echo "- Software → MAC Address (scroll down)"
echo ""

echo "📹 Security Cameras:"
echo ""
echo "Nest Cameras:"
echo "- Google Home app → Camera → Settings → Technical Info"
echo "- Look for 'MAC Address' or 'Wi-Fi MAC'"
echo ""
echo "Eufy Cameras:"
echo "- Eufy Security app → Camera → Settings → Device Info"
echo "- Look for 'MAC Address' or 'Wi-Fi Address'"
echo ""

echo "💻 Other Devices:"
echo "- Check device manual or network settings"
echo "- Router admin panel usually shows all connected devices with MACs"
echo ""

echo "📝 MAC Address Format:"
echo "----------------------"
echo "MAC addresses look like: XX:XX:XX:XX:XX:XX"
echo "Example: 12:34:56:78:9A:BC"
echo ""
echo "Make sure to:"
echo "- Note the exact format (with colons)"
echo "- Don't include any extra characters"
echo "- Copy carefully to avoid typos"
echo ""

echo "✅ Next Steps:"
echo "---------------"
echo "1. Gather MAC addresses for all your key devices"
echo "2. Access Asus router admin: http://192.168.1.1"
echo "3. Add static DHCP leases (see DNS_SETUP_GUIDE.md)"
echo "4. Test hostname resolution: ping mediaserver"
echo ""

echo "🎯 This will give you reliable name-based access to all devices!"

