  global:
    scrape_interval: 15s
    evaluation_interval: 30s
    external_labels:
      cluster: homelab

  rule_files:
    - /etc/prometheus/rules/*.yml

  alerting:
    alertmanagers:
      - static_configs:
          - targets: ["192.168.1.11:9093"]

  scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets: ["localhost:9090"]

    - job_name: node-exporter
      static_configs:
        - targets: ["192.168.1.11:9100"]
      scrape_interval: 30s

    - job_name: cadvisor
      static_configs:
        - targets: ["192.168.1.11:8081"]
      scrape_interval: 30s

    - job_name: plex
      static_configs:
        - targets: ["192.168.1.11:9594"]
      scrape_interval: 60s

    - job_name: adguard_dns_probe
      metrics_path: /probe
      params:
        module: [dns_adguard]
      static_configs:
        - targets: ["192.168.1.11:53"]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 192.168.1.11:9115
